@baseUrl = http://localhost:8080/auth
@accessToken  = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiX2lkIjoiNWY0Y2QzODUtMjJlOS00ZjRiLWJlZjQtM2ZmODRiOWFkYTBkIiwiaWF0IjoxNzMzOTI4OTQwLCJleHAiOjE3MzM5MzI1NDB9.g6plcMeBlfukfpOOuzCcGi_m_8U38PhReKTmjyvER1A
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiX2lkIjoiNWY0Y2QzODUtMjJlOS00ZjRiLWJlZjQtM2ZmODRiOWFkYTBkIiwiaWF0IjoxNzMzOTI4OTQwfQ.Ss2lr7CSPq3dMbPpzbSeGgBPk9cvOl2Qo9l0tJzx0ZA

### Register a New User
POST {{baseUrl}}/register HTTP/1.1
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "testpassword"
}

### Login with the Registered User
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "testpassword"
}

### Refresh Tokens
POST {{baseUrl}}/refresh HTTP/1.1
Authorization: JWT {{refreshToken}}
Content-Type: application/json

{}

### Logout the User
POST {{baseUrl}}/logout HTTP/1.1
Authorization: JWT {{refreshToken}}
Content-Type: application/json

{}
