### Create a new post
POST http://localhost:8080/posts HTTP/1.1
Content-Type: application/json

{
  "_id": 1,
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "sender": "JohnDoe"
}

###

### Create another post
POST http://localhost:8080/posts HTTP/1.1
Content-Type: application/json

{
  "_id": 2,
  "title": "My Second Post",
  "content": "Content of the second post.",
  "sender": "JaneDoe"
}

### Get all posts
GET http://localhost:8080/posts HTTP/1.1
Content-Type: application/json

###

### Get all posts by a specific sender
GET http://localhost:8080/posts?sender=JohnDoe HTTP/1.1
Content-Type: application/json

###

### Get a post by ID
GET http://localhost:8080/posts/1 HTTP/1.1
Content-Type: application/json

###

### Get the updated post by ID
GET http://localhost:8080/posts/1 HTTP/1.1
Content-Type: application/json

###

### Get all posts (to check both posts exist)
GET http://localhost:8080/posts HTTP/1.1
Content-Type: application/json

###
